services:
  db:
    image: postgres
    container_name: fastory-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - fastory_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  fastory_pgdata: